{% set name = "fastlowess" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7892d0aaba39bf1e547eb7e0deae3498a9cbb59017bf75f3e01fc634c47ae53b

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - numpy >=1.20.0

test:
  imports:
    - fastlowess

about:
  home: https://github.com/thisisamirv/fastLowess-py
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Fast LOWESS implementation in Rust with Python bindings

extra:
  recipe-maintainers:
    - thisisamirv
