{% set name = "fastlowess" %}
{% set version = "0.99.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcebcc128fc717e4740782892b9306a3c0c0a60025baa2502cd7622ccdb8fc68

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
  run:
    - python
    - numpy >=1.20.0

test:
  imports:
    - fastlowess

about:
  home: https://github.com/thisisamirv/lowess-project
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: High-performance LOWESS smoothing for Rust, Python, and R

extra:
  recipe-maintainers:
    - thisisamirv
